name: rekorddart
description: A Dart library for accessing Rekordbox databases.
version: 1.0.2
repository: https://github.com/jeroen-meijer/rekorddart
license: MIT
topics:
  - music
  - dj
  - rekordbox
  - spotify

environment:
  sdk: '>=3.10.1 <4.0.0'

dependencies:
  cli_table: ^1.0.2
  drift: ^2.29.0
  meta: ^1.17.0
  path: ^1.9.1
  sqlite3: ^2.9.4
  uuid: ^4.5.2
  xml: ^6.6.1

dev_dependencies:
  build_runner: ^2.10.4
  drift_dev: ^2.29.0
  lints: ^6.0.0
  test: ^1.27.0
  very_good_analysis: ^10.0.0

executables:
  download_key: download_key
